version: '3.8'

services:
  # NestJS CRM Backend
  crm-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=test123
      - DB_NAME=simple_crm
      - JWT_SECRET=docker_jwt_secret_change_in_production
      - JWT_EXPIRES_IN=24h
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - crm-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: SimpleCRM
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=simple_crm
      - MYSQL_USER=crm_user
      - MYSQL_PASSWORD=crm_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    networks:
      - crm-network

  # phpMyAdmin (optional - for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=test123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - crm-network

volumes:
  mysql_data:

networks:
  crm-network:
    driver: bridge